package com.shiftapp.roles;

public enum Permission {
    SHIFT_VIEW,

    ATTENDANCE_VIEW, ATTENDANCE_EDIT, ATTENDANCE_DELETE,

    EMPLOYEE_VIEW, EMPLOYEE_CREATE, EMPLOYEE_EDIT, EMPLOYEE_DELETE,

    WORKPLACE_VIEW, WORKPLACE_CREATE, WORKPLACE_EDIT, WORKPLACE_DELETE,
    POSITION_VIEW, POSITION_CREATE, POSITION_EDIT, POSITION_DELETE,
    DEPARTMENT_VIEW, DEPARTMENT_CREATE, DEPARTMENT_EDIT, DEPARTMENT_DELETE,
    BREAK_RULE_VIEW, BREAK_RULE_CREATE, BREAK_RULE_EDIT, BREAK_RULE_DELETE,
    ATTENDANCE_STATUS_VIEW, ATTENDANCE_STATUS_CREATE, ATTENDANCE_STATUS_EDIT, ATTENDANCE_STATUS_DELETE,

    NOTIFICATION_VIEW, NOTIFICATION_EDIT,

    LOGGING_VIEW
}