-- V1: Начальная схема — рестораны, пользователи, предпочтения

CREATE TABLE IF NOT EXISTS restaurants (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(200) NOT NULL,
    timezone   VARCHAR(64)  NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT       NOT NULL REFERENCES restaurants(id),
    login         VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(30)  NOT NULL CHECK (role IN ('STAFF','MANAGER','ADMIN')),
    full_name     VARCHAR(200) NOT NULL,
    active        BOOLEAN      NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL,
    CONSTRAINT ukow0gan20590jrb00upg3va2fn UNIQUE (login)
);

CREATE TABLE IF NOT EXISTS preferences (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT      NOT NULL REFERENCES restaurants(id),
    employee_id   BIGINT      NOT NULL REFERENCES users(id),
    work_date     DATE        NOT NULL,
    is_off        BOOLEAN     NOT NULL DEFAULT FALSE,
    status        VARCHAR(30) NOT NULL CHECK (status IN ('DRAFT','SUBMITTED','APPROVED','REJECTED')),
    comment       VARCHAR(500),
    created_at    TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS week_status (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT       NOT NULL REFERENCES restaurants(id),
    week_start    DATE         NOT NULL,
    status        VARCHAR(255) NOT NULL CHECK (status IN ('RECEIVING','DRAFTING','CONFIRMED')),
    updated_by_id BIGINT REFERENCES users(id),
    updated_at    TIMESTAMPTZ  NOT NULL,
    CONSTRAINT ukmml2qjms8ug2kongjv7vafcr0 UNIQUE (restaurant_id, week_start)
);