-- V6: Таблица учёта рабочего времени (打刻システム)

CREATE TABLE IF NOT EXISTS time_records (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT      NOT NULL REFERENCES restaurants(id),
    user_id       BIGINT      NOT NULL REFERENCES users(id),
    record_type   VARCHAR(20) NOT NULL CHECK (record_type IN ('CLOCK_IN','CLOCK_OUT','BREAK_START','BREAK_END')),
    recorded_at   TIMESTAMPTZ NOT NULL,
    work_date     DATE        NOT NULL,
    photo_path    VARCHAR(255),
    note          VARCHAR(500),
    edited_by_id  BIGINT      REFERENCES users(id),
    edited_at     TIMESTAMPTZ
);

CREATE INDEX idx_time_records_user_date
    ON time_records(user_id, work_date);

CREATE INDEX idx_time_records_restaurant_date
    ON time_records(restaurant_id, work_date);